INSERT INTO professor (`EMP_NUM`, `EMP_FNAME`, `EMP_LNAME`, `EMP_DOB`, `DEPT_CODE`, `PROF_EXTENSION`) 
VALUES (101, 'Charles', 'Xavier', '1975-05-04 00:00:00', 'CIS', null),
 (702,'Dr.Stephen','Strange','1988-07-04 00:00:00','BIOL','7702');

INSERT INTO student (`STU_NUM`, `STU_FNAME`, `STU_LNAME`, `STU_DOB`, `STU_CLASS`, `STU_GPA`, `DEPT_CODE`, `EMP_NUM`)
VALUES (773355,'Thanawath','Huayhongthong','2001-10-08','SEC 1','4.00','CIS','702');

UPDATE student
set STU_NUM = 101
where STU_NUM = 773355;

UPDATE professor
set PROF_EXTENSION = 0077
where EMP_NUM = 101;

DELETE FROM professor
where EMP_NUM = 702;

SELECT*
FROM student;

SELECT EMP_FNAME , EMP_LNAME , DEPT_CODE
FROM professor
where DEPT_CODE = "CIS";

SELECT EMP_FNAME , EMP_LNAME
FROM professor
where EMP_FNAME like "%M%" and EMP_LNAME like "%M%";

SELECT STU_FNAME , STU_LNAME , DEPT_CODE
FROM STUDENT
WHERE DEPT_CODE = "ENG" 
OR DEPT_CODE = "ART" 
OR DEPT_CODE = "SOC" 
OR DEPT_CODE = "HIST"
order by DEPT_CODE ASC;

SELECT COURSE_CODE , COURSE_NAME , (CRS_CREDIT*250) AS TUITIONFEE , DEPT_CODE
FROM course
WHERE COURSE_NAME LIKE "%INTRO.%"
ORDER BY DEPT_CODE ASC; 

SELECT distinct COURSE_CODE , CLASS_ROOM
FROM CLASS
WHERE CLASS_ROOM LIKE "%KLR%" AND CLASS_CODE BETWEEN 20000 AND 30000;